Add --remove option to oci-ctl load
Elektrobit/oci-pilot pull request #34
Opened 2023-01-13 21:23 UTC by schaefi

Allow to remove the given OCI image file after it has been loaded into the local registry

2023-01-13 21:30 UTC, isbm requested changes
Not sure.

2023-01-13 21:30 UTC, isbm commented on doc/oci-ctl-load.rst
> +  local registry.
Confusing, TBH. You probably mean "clean" in this case.

2023-01-13 21:44 UTC, schaefi commented on doc/oci-ctl-load.rst
> +  local registry.
Sorry but I disagree. This is not a cleanup. Actually cleanup is misleading because we are not cleaning up we are removing a file from the system and the user should specify this with an option that makes it crystal clear.
The option name and the help text to it is from my perspective absolutely clear:

```
oci-ctl load --oci /some/oci-image-file
```

User expectation is ```/some/oci-image-file``` stays on the system

```
oci-ctl load --oci /some/oci-image-file --remove
```

User expectation is at least "something gets removed". What gets removed: ```oci-ctl load --help```
```
oci-ctl-load 1.0.1
Load container

USAGE:
    oci-ctl load [OPTIONS] --oci <OCI>

OPTIONS:
    -h, --help         Print help information
        --oci <OCI>    OCI image to load into local podman registry
        --remove       Remove given OCI image after loading to local registry
    -V, --version      Print version information
```

For me this is crystal clear

Now you say call it ```--clean```. So you want

```
oci-ctl load --oci /some/oci-image-file --clean
```

Nothing here indicates that your input file gets deleted. Actually this --clean sounds harmless but it is not.
So no --clean is not good

2023-01-13 21:53 UTC, isbm commented on doc/oci-ctl-load.rst
> +  local registry.
Then I don't understand how to use it and what does it do, because `load` and then `remove` and the same time is very contradicting.

So what does it do anyways? The source tar after it gets loaded? Well, then this action then means "cleanup the leftovers". You can do the other way around: `--keep-src` or so, and always delete image file by default.

But currently it means to me "go to documentation, memorise what this action do, then write it down in your own words so next time you actually understand that".

2023-01-13 21:56 UTC, isbm commented on doc/oci-ctl-load.rst
> +  local registry.
Also your English in the help... I read it like so:
1. Load OCI image to the registry
2. REmove it afterwards from the registry

Srsly, I am really confused what does it all mean... 😆

2023-01-13 22:16 UTC, schaefi commented on doc/oci-ctl-load.rst
> +  local registry.
Man it seems like you did not understand what load does. Load loads the given container image file into the local podman registry. I mean it cannot be expressed any clearer. What does that mean. It means

```
podman load some-oci-tar-file
```
podman takes this file and integrates it as a container image into its registry. The registry is the data you find on your system below ```/var/lib/containers/storage``` Once some-oci-tar-file is part of your registry you probably don't need it anymore. That's why you can remove it after this load action, and that's why this option now exists

> Also your English in the help... I read it like so:

sorry but this is simply not true:

```
--oci <OCI>    OCI image to load into local podman registry
--remove       Remove given OCI image after loading to local registry
```

What is so hard to understand ?

2023-01-13 22:29 UTC, isbm commented on doc/oci-ctl-load.rst
> +  local registry.
"Clean", adverb
1. so as to be free from dirt, marks, or unwanted matter.
"the room had been washed clean"

If it is `--clean` or `--cleanup` then to me it intuitively sounds like "remove that tar file after being done". Meanwhile `--remove` can be whatever: remove image from the registry, remove file, remove both etc, so it forces me to precisely remember the action.

OK, whatever. I don't care anymore. 😉

2023-01-14 09:07 UTC, schaefi commented on doc/oci-ctl-load.rst
> +  local registry.
First I'm sorry if the conversation turned too harsh. It wasn't my intention to offend you. I'm just tired about this sort of conversation for a super simple change and when I think it should be crystal clear

Obviously it's not clear and I still disagree with your idea to call it a cleanup. Like you explained, the word "clean" means getting rid of something unwanted. The oci image file used to get loaded into the local registry is however not dirt or unwanted. It is under certain conditions no longer needed and can then be removed. What those conditions are is not known to oci-ctl. Thus I added an option for the user.

I would have never guessed that it could be that much of a problem. Anyway we cannot come to an agreement here and that's ok for me too, because I can at any time just call ```oci-ctl load file``` followed by ```rm file```.

Therefore I'm closing this now

2023-01-14 09:08 UTC, closed without merging

2023-01-17 12:51 UTC, isbm commented on doc/oci-ctl-load.rst
> +  local registry.
No really need to close it. You can merge with `--remove`. I just expressed concern that in case of a new inexperienced packager, who won't read `--help` or documentation (as usual), but will follow already made Flakes as an example.

And so at least for me, it would be much more intuitive to read one of there:

    oci-pilot load --oci=/image/file --rm-oci-tar
    oci-pilot load --oci=/image/file --remove-oci-tar
    oci-pilot load --oci=/image/file --cleanup

Or use short options (that will force packager to read the documentation):

    oci-pilot load --oci=/image/file -r

To me, those all parameters always reads as functions. Would you create a function in C, called `remove()`? Or you would rather call it `remove_allocated_memory` instead? Even if that would be a method to a class, `load.remove()` is "a bit" weird to me.

So that's the point: how to make it more intuitive for newbies, who will just look at the script and basically copypaste that (as they always do)? Ofc there is a documentation, but how do we still do it more intuitive and quick-grasp-able? Because we will have much more options in a future and people will have to _learn all that_ explicitly with the documentation — a learning curve I would like to see at least minimised to a very point.