Added SBOM creation as github action
Elektrobit/oci-pilot pull request #38
Opened 2023-02-27 10:58 UTC by schaefi

Use sbom4rust python module to create a software bill of materials to allow CVE source scanning based on it

2023-02-27 12:18 UTC, isbm requested changes
Just a question.

2023-02-27 12:18 UTC, isbm commented on .github/workflows/ci-sbom.yml
> +          cargo bom
Shouldn't it be like `cargo bom > BOM.txt` instead? So it produces something [like this](https://github.com/sensorfu/cargo-bom/blob/HEAD/BOM.txt)?

2023-02-27 12:20 UTC, schaefi commented on .github/workflows/ci-sbom.yml
> +          cargo bom
well you said we should have something for later. There is currently no consumer of this information and also nobody can tell in what shape or form it should be delivered. Therefore please don't let us populate this data in any other place than the github action artifacts. That's enough for the moment. Thanks

2023-02-28 10:18 UTC, isbm commented on .github/workflows/ci-sbom.yml
> +          cargo bom
That's a very good question what to do _next_ with it. 😉 Let's follow up then.

2023-02-28 10:25 UTC, isbm approved these changes

2023-02-28 10:27 UTC, schaefi commented on .github/workflows/ci-sbom.yml
> +          cargo bom
yep

2023-02-28 10:27 UTC, merged